pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage("SonarQube"){
            steps{
                script{
                    try{
                        echo "Analizando el proyecto con SonarQube."
                        withSonarQubeEnv("Sonar Server"){
                            sh "mvn sonar:sonar"
                        }
                    } catch (err){
                        echo "The SonarQube analysis failed"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
