pipeline {
    stages {        
        stage("SonarQube"){            
            steps{
                script{
                    try{
                        echo "Analizando el proyecto con SonarQube."
                        withSonarQubeEnv("Sonar Server"){
                            sh "mvn clean package sonar:sonar"
                        }
                    } catch (err){
                        echo err.toString()
                        echo "The SonarQube analysis failed"
                    }
                }
            }
        }      
    }
}
